# Generated by Django 5.2.3 on 2025-07-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_01', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
