# Generated by Django 5.2.3 on 2025-07-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='phone_number',
            new_name='phone_01',
        ),
    ]
